'use strict';
const VERSION='bw2-shiny-journey-mvp-1';
const DB='bw2ShinyJourneyDB_v1',STORE='snapshots',KEY='current';
const CHANNEL='bw2-shiny-journey-live-v1';
const bc='BroadcastChannel'in window?new BroadcastChannel(CHANNEL):null;
const species={
 patrat:{no:504,name:'ミネズミ',need:2,uses:['ミネズミとして残す','ミルホッグへ進化'],sprite:504},
 purrloin:{no:509,name:'チョロネコ',need:2,uses:['チョロネコとして残す','レパルダスへ進化'],sprite:509},
 lillipup:{no:506,name:'ヨーテリー',need:3,uses:['ヨーテリーとして残す','ハーデリアへ進化','ムーランドへ進化'],sprite:506},
 azurill:{no:298,name:'ルリリ',need:3,uses:['ルリリとして残す','マリルへ進化','マリルリへ進化'],sprite:298},
 mareep:{no:179,name:'メリープ',need:3,uses:['メリープとして残す','モココへ進化','デンリュウへ進化'],sprite:179},
 psyduck:{no:54,name:'コダック',need:2,uses:['コダックとして残す','ゴルダックへ進化'],sprite:54},
 pidove:{no:519,name:'マメパト',need:3,uses:['マメパトとして残す','ハトーボーへ進化','ケンホロウへ進化'],sprite:519},
 riolu:{no:447,name:'リオル',need:2,uses:['リオルとして残す','ルカリオへ進化'],sprite:447}
};
const areas={
 route19:{name:'19番道路',order:1,note:'通常草むら・B2/W2共通',encounters:[['patrat',50],['purrloin',50]]},
 ranch:{name:'サンギ牧場',order:2,note:'通常草むら・B2/W2共通',encounters:[['lillipup',40],['azurill',20],['patrat',10],['mareep',10],['psyduck',10],['pidove',5],['riolu',5]]}
};
const fresh=()=>({version:VERSION,updatedAt:new Date().toISOString(),area:'route19',mode:'dual',devices:{b2:{label:'BLACK 2',target:'purrloin',encounters:0,total:0},w2:{label:'WHITE 2',target:'purrloin',encounters:0,total:0}},captures:[
 {id:crypto.randomUUID(),species:'patrat',at:new Date().toISOString(),area:'route19',version:'B2',device:'b2',method:'通常草むら',encounters:0,purpose:'ミネズミとして残す',offTarget:false,memo:'開始時データ'},
 {id:crypto.randomUUID(),species:'patrat',at:new Date().toISOString(),area:'route19',version:'W2',device:'w2',method:'通常草むら',encounters:0,purpose:'ミルホッグへ進化',offTarget:false,memo:'開始時データ'},
 {id:crypto.randomUUID(),species:'purrloin',at:new Date().toISOString(),area:'route19',version:'B2',device:'b2',method:'通常草むら',encounters:0,purpose:'チョロネコとして残す',offTarget:false,memo:'開始時データ'}
 ],session:null,history:[]});
let state=fresh(),pendingDevice='b2',sessionTick=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${species[id].sprite}.png`;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function readState(){const db=await openDB();try{return await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}finally{db.close()}}
async function writeState(){state.updatedAt=new Date().toISOString();const db=await openDB();try{await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(structuredClone(state),KEY);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error)});if($('.saveState')){$('#saveState').textContent='● 保存済み';$('#saveState').className='save ok'}bc?.postMessage({type:'state',state})}finally{db.close()}}
async function commit(action){if($('.saveState')){$('#saveState').textContent='● 保存中';$('#saveState').className='save busy'}try{await writeState();render();if(action)bc?.postMessage({type:'effect',effect:action})}catch(e){alert('保存に失敗しました。画面を閉じずJSONを書き出してください。\n'+e.message);throw e}}
const count=id=>state.captures.filter(x=>x.species===id).length;
const areaProgress=id=>{const list=areas[id].encounters;const need=list.reduce((n,[p])=>n+species[p].need,0);const got=list.reduce((n,[p])=>n+Math.min(count(p),species[p].need),0);return{got,need,pct:need?got/need*100:0}};
const overall=()=>{const ids=[...new Set(Object.values(areas).flatMap(a=>a.encounters.map(x=>x[0])))];const need=ids.reduce((n,p)=>n+species[p].need,0);const got=ids.reduce((n,p)=>n+Math.min(count(p),species[p].need),0);return{got,need,pct:got/need*100}};
function options(area,current){return areas[area].encounters.map(([id,rate])=>`<option value="${id}" ${id===current?'selected':''}>${species[id].name}（${rate}%・${count(id)}/${species[id].need}）</option>`).join('')}
function renderAdmin(){const o=overall();$('#overall').textContent=`${o.got} / ${o.need}`;$('#overallPct').textContent=o.pct.toFixed(1)+'%';$('#overallBar').style.width=o.pct+'%';$('#areaSelect').innerHTML=Object.entries(areas).map(([id,a])=>`<option value="${id}" ${id===state.area?'selected':''}>${a.name}</option>`).join('');$('#modeSelect').value=state.mode;
 const shown=state.mode==='single'?['b2']:['b2','w2'];$('#devices').innerHTML=shown.map(id=>{const d=state.devices[id],p=species[d.target];return`<article class="device ${id}"><div class="device-head"><h3>${d.label}</h3><span>${id==='b2'?'1台目':'2台目'}</span></div><label class="target-picker">現在のターゲット<select data-target="${id}">${options(state.area,d.target)}</select></label><div class="counter"><div><small>${p.name} 個別遭遇数</small><strong>${d.encounters.toLocaleString()}</strong><small>通算 ${d.total.toLocaleString()}回</small></div><div class="counter-buttons"><button data-add="${id}" data-n="1">＋1</button><button data-add="${id}" data-n="10">＋10</button><button data-add="${id}" data-n="-1">−1</button></div></div><button class="capture" data-capture="${id}">✨ 色違い捕獲！</button></article>`}).join('');
 const running=state.session?.running;$('#sessionBtn').textContent=running?'セッション終了':'セッション開始';$('#sessionTotals').textContent=`B2 ${state.devices.b2.total}回 / W2 ${state.devices.w2.total}回`;renderSessionTime();renderAreas();renderRecords();bindDynamic()}
function renderAreas(){const root=$('#areaCards');if(!root)return;root.innerHTML=Object.entries(areas).map(([aid,a])=>{const pr=areaProgress(aid);return`<article class="area-card"><div class="area-heading"><div><span class="label">AREA ${a.order}</span><h2>${a.name}</h2><small>${a.note}</small></div><b>${pr.got}/${pr.need}・${pr.pct.toFixed(1)}%</b></div><div class="encounters">${a.encounters.map(([id,rate])=>{const p=species[id],n=count(id);return`<div class="encounter ${n>=p.need?'complete':''}"><img class="sprite" src="${sprite(id)}"><div><strong>${p.name} <small>${rate}%</small></strong><small>${p.uses.join('・')}</small></div><span class="count">${n}/${p.need}</span></div>`}).join('')}</div></article>`}).join('')}
function renderRecords(){if(!$('#recordList'))return;$('#recordCount').textContent=`${state.captures.length}件`;$('#recordList').innerHTML=[...state.captures].reverse().map(r=>`<div class="record"><small>${new Date(r.at).toLocaleString('ja-JP')}</small><b>${species[r.species]?.name||r.species}<small>${areas[r.area]?.name}・${r.version}・${r.encounters}回</small></b><span>${r.purpose}</span></div>`).join('')||'<p>まだ捕獲記録がありません。</p>'}
function bindDynamic(){$$('[data-target]').forEach(x=>x.onchange=async()=>{state.devices[x.dataset.target].target=x.value;await commit()});$$('[data-add]').forEach(x=>x.onclick=async()=>{const d=state.devices[x.dataset.add],n=Number(x.dataset.n);d.encounters=Math.max(0,d.encounters+n);d.total=Math.max(0,d.total+n);await commit('tick')});$$('[data-capture]').forEach(x=>x.onclick=()=>openCapture(x.dataset.capture))}
function openCapture(dev){pendingDevice=dev;const d=state.devices[dev],p=species[d.target];$('#captureWho').innerHTML=`<div class="encounter"><img class="sprite" src="${sprite(d.target)}"><div><strong>${p.name}</strong><small>${areas[state.area].name}・${d.label}・${d.encounters}回</small></div></div>`;$('#capturePurpose').innerHTML=p.uses.map((x,i)=>`<option ${i===Math.min(count(d.target),p.uses.length-1)?'selected':''}>${x}</option>`).join('');$('#captureMemo').value='';$('#captureDialog').showModal()}
async function capture(){const d=state.devices[pendingDevice],id=d.target,p=species[id],before=count(id);state.captures.push({id:crypto.randomUUID(),species:id,at:new Date().toISOString(),area:state.area,version:pendingDevice==='b2'?'B2':'W2',device:pendingDevice,method:'通常草むら',encounters:d.encounters,purpose:$('#capturePurpose').value,offTarget:false,memo:$('#captureMemo').value});d.encounters=0;await commit(before+1>=p.need?'complete':'capture');toast(`${p.name}を登録しました`)}
function renderSessionTime(){if(!$('#sessionTime'))return;const s=state.session;if(!s){$('#sessionTime').textContent='00:00:00';return}const end=s.running?Date.now():(s.endedAt||Date.now()),sec=Math.floor((end-s.startedAt)/1000);$('#sessionTime').textContent=[Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(x=>String(x).padStart(2,'0')).join(':')}
async function toggleSession(){if(state.session?.running){state.session.running=false;state.session.endedAt=Date.now();state.history.push(structuredClone(state.session))}else state.session={running:true,startedAt:Date.now(),area:state.area,startTotals:{b2:state.devices.b2.total,w2:state.devices.w2.total}};await commit('session')}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function renderOBS(){if(state.area==='ranch'&&state.mode==='dual')return renderReferenceRanch();const a=areas[state.area],pr=areaProgress(state.area),shown=state.mode==='single'?['b2']:['b2','w2'],totalRE=shown.reduce((n,id)=>n+state.devices[id].encounters,0),rare=a.encounters.reduce((x,y)=>y[1]<x[1]?y:x)[0],next=a.encounters.find(([id])=>count(id)<species[id].need)?.[0];$('#obsRoot').innerHTML=`<div class="obs-stage area-${state.area}"><div class="pixel-scene"><i class="hill h1"></i><i class="hill h2"></i><i class="barn"></i><i class="fence"></i></div><header class="obs-top"><div class="journey-title"><span class="ball-mark"></span><b>BW<span>2</span></b><em>SHINY JOURNEY</em></div><div class="obs-place"><small>CURRENT AREA</small><h1>${a.name}</h1><i>LIVE</i></div></header><div class="screens ${state.mode}">${shown.map((id,i)=>{const d=state.devices[id],p=species[d.target];return`<section class="game-unit ${id}"><div class="game-label"><span>${d.label}</span><small>3DS ${i+1}</small></div><div class="game-window"><div class="capture-guide">GAME CAPTURE</div></div><div class="game-hud"><div><img src="${sprite(d.target)}"><span><small>TARGET</small><strong>${p.name}</strong></span></div><b>${d.encounters.toLocaleString()}<small> ENCOUNTERS</small></b></div></section>`}).join('')}</div><footer class="lower-deck"><section class="collection-hud"><div class="hud-title"><b>${a.name}・捕獲状況</b><span>通常草むら</span></div><div class="poke-grid">${a.encounters.map(([id,rate])=>{const p=species[id],n=count(id),target=shown.some(d=>state.devices[d].target===id);return`<div class="poke-chip ${n>=p.need?'complete':''} ${target?'target':''}"><span class="rate">${rate}%</span><img src="${sprite(id)}"><b>${p.name}</b><strong>${n}<i>/</i>${p.need}</strong></div>`}).join('')}</div></section><aside class="stream-status"><div class="status-progress"><small>AREA PROGRESS</small><strong>${pr.pct.toFixed(1)}%</strong><span><i style="width:${pr.pct}%"></i></span><b>${pr.got} / ${pr.need}</b></div><div class="mini-stats"><div><small>NOW</small><b>${totalRE.toLocaleString()} RE</b></div><div><small>RARE SLOT</small><b>${species[rare].name} ${a.encounters.find(x=>x[0]===rare)[1]}%</b></div></div><div class="next-target"><small>NEXT TARGET</small><b>${next?species[next].name:'AREA COMPLETE'}</b></div></aside></footer></div>`}
function effect(kind){const root=$('#obsRoot');root?.classList.add('pulse');setTimeout(()=>root?.classList.remove('pulse'),220);if(kind==='capture'||kind==='complete'){const c=$('#celebration');c.textContent=kind==='complete'?'COMPLETE!':'SHINY GET!';c.classList.remove('go');void c.offsetWidth;c.classList.add('go')}}
function render(){document.body.classList.contains('obs')?renderOBS():renderAdmin()}
async function init(){const saved=await readState();if(saved)state=saved;render();bc?.addEventListener('message',e=>{if(e.data.type==='state'){state=e.data.state;render()}if(e.data.type==='effect')effect(e.data.effect)});if(document.body.classList.contains('admin'))bindAdmin();sessionTick=setInterval(async()=>{renderSessionTime();if(document.body.classList.contains('obs')){const s=await readState();if(s&&s.updatedAt!==state.updatedAt){state=s;render()}}},1000)}
function bindAdmin(){$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#areaSelect').onchange=async e=>{state.area=e.target.value;for(const d of Object.values(state.devices))if(!areas[state.area].encounters.some(x=>x[0]===d.target))d.target=areas[state.area].encounters[0][0];await commit('area')};$('#modeSelect').onchange=async e=>{state.mode=e.target.value;await commit()};$('#sessionBtn').onclick=toggleSession;$('#confirmCapture').onclick=async e=>{e.preventDefault();await capture();$('#captureDialog').close()};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'BW2 SHINY JOURNEY',version:VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bw2-shiny-journey-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const d=JSON.parse(r.result),incoming=d.state||d;if(!incoming.devices||!Array.isArray(incoming.captures))throw Error('BW2 SHINY JOURNEYのデータではありません');state=incoming;await commit();alert(`復元完了：捕獲記録 ${state.captures.length}件`)}catch(err){alert('復元できませんでした：'+err.message)}};r.readAsText(f)}}
init().catch(e=>{console.error(e);alert('起動に失敗しました：'+e.message)});

function renderReferenceRanch(){
 const a=areas.ranch,pr=areaProgress('ranch'),rare='riolu';
 const total=state.devices.b2.encounters+state.devices.w2.encounters;
 $('#obsRoot').innerHTML=`<div class="reference-stage">
  <div class="reference-cards">${a.encounters.map(([id,rate],i)=>{const p=species[id],n=count(id),target=state.devices.b2.target===id||state.devices.w2.target===id;return`<div class="reference-card ${n>=p.need?'complete':''} ${target?'target':''}" style="--slot:${i}"><img src="${sprite(id)}"><b>${p.name}</b><span>${rate}%</span><strong>${n}/${p.need}</strong></div>`}).join('')}</div>
  <div class="reference-rare"><img src="${sprite(rare)}"><b>${species[rare].name} 5%</b><strong>必要数 ${species[rare].need}匹</strong></div>
  <div class="reference-encounter"><b>${total.toLocaleString()}</b><span>回</span></div>
  <div class="reference-progress"><b>${pr.pct.toFixed(1)}%</b><span>${pr.got}/${pr.need}</span></div>
  <div class="reference-device ref-b2"><b>${species[state.devices.b2.target].name}</b><span>${state.devices.b2.encounters.toLocaleString()} RE</span></div>
  <div class="reference-device ref-w2"><b>${species[state.devices.w2.target].name}</b><span>${state.devices.w2.encounters.toLocaleString()} RE</span></div>
 </div>`
}
